### ISSUE TITLE
Display short title of next appointment

### ISSUE THREAD

**Issue by made4this** [le-cds/connectiq-faceymcwatchface#23]
How about to show a small/fixed number of letters of the title of the next appointment?

**Comment by le-cds** [comment]
This would certainly be possible. There are two ways of showing more info, but both only make sense if appointments are assigned to the center indicator:

* Display the title on a new line. This would require lots of additional space, which will run contrary to #22 which argues for larger fonts and thus less available space.
* Display the title after the time. I feel this will kill off the cleanliness of the watch face since the time is not always where one expects it.

I'll have to think about this some more, but I'm not sure whether a good compromise can be had here.
